# Generated by Django 2.0.2 on 2018-07-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='result',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'OnGoing'), ('2', 'Finished'), ('3', 'Errror')], default='0', max_length=1),
        ),
    ]
