# Generated by Django 2.0.2 on 2018-02-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='submission_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='win_number',
            field=models.IntegerField(default=0),
        ),
    ]
