# Generated by Django 2.1 on 2018-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_game_max_player_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='server_response',
            field=models.TextField(default=''),
        ),
    ]
