# Generated by Django 2.1 on 2018-08-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_game_server_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_records',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='game_result',
            field=models.TextField(default=''),
        ),
    ]
