# Generated by Django 2.1 on 2018-09-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20180813_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='max_player_num',
        ),
        migrations.AddField(
            model_name='gametype',
            name='max_player_num',
            field=models.IntegerField(default=2),
        ),
    ]
